### ISSUE TITLE
Unable to save configurations in Post-build Actions - Deploy with XL Deploy 

### ISSUE THREAD

**Issue by pratidnya2019** [xebialabs-community/xld-xldeploy-plugin#7]
Unable to save configurations in Post-build Actions - Deploy with XL Deploy 
Getting below error log 

java.lang.IllegalArgumentException: Unable to convert to class com.xebialabs.deployit.ci.JenkinsImportOptions
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:742)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:479)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:788)
Caused: java.lang.IllegalArgumentException: Failed to convert the importOptions parameter of the constructor public com.xebialabs.deployit.ci.DeployitNotifier(java.lang.String,java.lang.String,java.lang.String,com.xebialabs.deployit.ci.JenkinsPackageOptions,com.xebialabs.deployit.ci.JenkinsImportOptions,com.xebialabs.deployit.ci.JenkinsDeploymentOptions,boolean,java.util.List,com.xebialabs.deployit.ci.Credential)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:790)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:84)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:679)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class com.xebialabs.deployit.ci.DeployitNotifier from {"credential":"DeployIt","application":"Applications/MktPartAPI/partsmk1\"","version":"test2","verbose":false,"importOptions":false,"":"0","mode":{"stapler-class":["com.xebialabs.deployit.ci.GeneratedLocation","com.xebialabs.deployit.ci.FileSystemLocation","com.xebialabs.deployit.ci.URLLocation"],"$class":["com.xebialabs.deployit.ci.GeneratedLocation","com.xebialabs.deployit.ci.FileSystemLocation","com.xebialabs.deployit.ci.URLLocation"]},"deploymentOptions":false,"environment":"","versionKind":"Packaged","generateDeployedOnUpgrade":true,"skipMode":false,"testMode":false,"rollbackOnError":false,"stapler-class":"com.xebialabs.deployit.ci.DeployitNotifier","$class":"com.xebialabs.deployit.ci.DeployitNotifier"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:682)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:479)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:475)
	at hudson.model.Descriptor.newInstance(Descriptor.java:598)
Caused: java.lang.Error: Failed to instantiate class com.xebialabs.deployit.ci.DeployitNotifier from {"credential":"DeployIt","application":"Applications/MktPartAPI/partsmk1\"","version":"test2","verbose":false,"importOptions":false,"":"0","mode":{"stapler-class":["com.xebialabs.deployit.ci.GeneratedLocation","com.xebialabs.deployit.ci.FileSystemLocation","com.xebialabs.deployit.ci.URLLocation"],"$class":["com.xebialabs.deployit.ci.GeneratedLocation","com.xebialabs.deployit.ci.FileSystemLocation","com.xebialabs.deployit.ci.URLLocation"]},"deploymentOptions":false,"environment":"","versionKind":"Packaged","generateDeployedOnUpgrade":true,"skipMode":false,"testMode":false,"rollbackOnError":false,"stapler-class":"com.xebialabs.deployit.ci.DeployitNotifier","$class":"com.xebialabs.deployit.ci.DeployitNotifier"}

Appreciate your help

**Comment by pratidnya2019** [comment]
Issue resolved
